# Etapa 1: Ejecutar pruebas y empaquetar
FROM maven:3.6-jdk-8 as build
WORKDIR /app
COPY . .
RUN mvn clean package

# Etapa 2: Ejecutar el microservicio
FROM openjdk:8-jre
WORKDIR /app
COPY --from=build /app/target/*.war app.war
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.war"]
